export const CATEGORIES = [
  'REFERENCE', 'DOWNLOAD', 'SPORTS', 'GAMES', 'MUSIC',
  'MOVIES', 'BLOG', 'CAREER', 'STORE', 'TOOLS',
  'POPULAR', 'TECH.'
] as const;

export const NAVIGATION_ITEMS = [
  'CATEGORIES',
  'INFORMATION',
  'REGISTER',
  'LOGIN',
  'CONTACT US',
  'MAKE THIS MY HOMEPAGE'
] as const;